name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'prueba3/index.html'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'prueba3/index.html'
jobs:

  build-container:
    name: Build conteiner

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
    - name: Build and push Docker hub
      uses: docker/build-push-action@v3.2.0
      with: 
        context: ./prueba3
        push: true
        tags: mksguti/prueba3:latest, mksguti/prueba3:${{ github.run_number }}
